server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    username: your_gmail@gmail.com
    password: mxmiujqrxzgfdabc
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
            required: true
